### PR TITLE
Fix console output problem, dotnet test appeared to hang

### LINKED ISSUE #100: `dotnet test` hangs indefinitely when running a multi-targeted assembly
**Version Information**
Version of Akka.NET? v1.4.27, Akka.MultiNodeTestRunner 1.0
Which Akka.NET Modules? Akka.Cluster.TestKit

**Describe the bug**
When attempting to run any of the built-in Akka.NET multinode tests, i.e. https://github.com/akkadotnet/akka.net/tree/dev/src/core/Akka.Cluster.Tests.MultiNode - which target multiple .NET versions, `dotnet test` will hang indefinitely without printing any output.

**To Reproduce**
Execute the the following command after cloning and checking out to https://github.com/akkadotnet/akka.net/tree/dev/src/core/Akka.Remote.Tests.MultiNode 

```
PS> dotnet test
```

I see the following output, and that's it:

```
  Akka.Remote.Tests.MultiNode -> D:\Repositories\olympus\akka.net\src\core\Akka.Remote.Tests.MultiNode\bin\Debug\net5.0\Akka.Remote.Tests.MultiNode.dll
Test run for D:\Repositories\olympus\akka.net\src\core\Akka.Remote.Tests.MultiNode\bin\Debug\net5.0\Akka.Remote.Tests.MultiNode.dll (.NETCoreApp,Version=v5.0)

Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
```

Nothing will happen. The test will just sit there.

This also doesn't work if I try to specify a target framework.

```
dotnet test -c Release --no-build --logger:trx --framework net5.0
```

Note: the tests run fine if I launch them via FAKE.

**Expected behavior**
I should immediately see some output from the `dotnet` test process.

**Actual behavior**
I don't see anything at all - it looks like the process is hanging.

**Screenshots**

image

**Environment**
Are you running on Linux? Windows? Docker? Which version of .NET?

Windows 10, using .NET 5 on both PowerShell and on the traditional DOS prompt.

### PR DESCRIPTION
**Pull request by Arkatufus**
Closes #100

### CODE REVIEW

File: src/Akka.MultiNode.TestAdapter/Internal/Sinks/FrameworkHandleMessageSinkActor.cs [hunk 1]
```diff
@@ -0,0 +1,212 @@
...
+using Akka.Actor;
+using Akka.Event;
+using Akka.MultiNode.TestAdapter.Internal.Reporting;
+using Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter;
+using Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging;
+using Microsoft.VisualStudio.TestPlatform.Utilities;
+
+namespace Akka.MultiNode.TestAdapter.Internal.Sinks
+{
+    public class FrameworkHandleMessageSinkActor: TestCoordinatorEnabledMessageSink
```
Comment (Arkatufus) [inline src/Akka.MultiNode.TestAdapter/Internal/Sinks/FrameworkHandleMessageSinkActor.cs:19]: New message sink for IFrameworkHandle

File: src/Akka.MultiNode.TestAdapter/Internal/Sinks/MessageSink.cs [hunk 2]
```diff
@@ -239,36 +239,45 @@ public void LogRunnerMessage(string message, string logSource, LogLevel level)
 
         public void Offer(string messageStr)
         {
-            var messageType = DetermineMessageType(messageStr);
-            if (messageType == MultiNodeTestRunnerMessageType.Unknown)
```
Comment (Arkatufus) [inline src/Akka.MultiNode.TestAdapter/Internal/Sinks/MessageSink.cs:243]: Convert if..else to switch structure

File: src/Akka.MultiNode.TestAdapter/Internal/Sinks/SinkCoordinator.cs [hunk 3]
```diff
@@ -192,7 +195,18 @@ private void PublishToChildren(RunnerMessage message)
         private void PublishToChildren(string message)
         {
             foreach (var sink in Sinks)
-                sink.Offer(message);
+            {
+                try
+                {
+                    sink.Offer(message);
+                }
+                catch (Exception e)
```
Comment (Arkatufus) [inline src/Akka.MultiNode.TestAdapter/Internal/Sinks/SinkCoordinator.cs:203]: If `sink.Offer()` ever threw, SinkCoordinator will die mid test, removing all of the message sinks, which will not be re-registered, since they're not the SinkCoordinator children.

File: src/Akka.MultiNode.TestAdapter/MultiNodeTestRunner.cs [hunk 4]
```diff
@@ -404,19 +419,8 @@ private void WaitForNodeExit(MultiNodeTestResult result, List<(NodeTest, Process
...
-                        timelineCollector.Tell(new TimelineLogCollectorActor.LogMessage(nodeInfo, eventArgs.Data));
-                        Console.WriteLine(eventArgs.Data);
-                        if (options.TeamCityFormattingOn)
-                        {
-                            // teamCityTest.WriteStdOutput(eventArgs.Data); TODO: open flood gates
-                        }
-                    }
-                };
+                opt.OutputDataReceived = OutputHandler;
+                opt.ErrorDataReceived = OutputHandler;
```
Comment (Arkatufus) [inline src/Akka.MultiNode.TestAdapter/MultiNodeTestRunner.cs:423]: Capture error outputs from test processes

File: src/Akka.MultiNode.TestAdapter/TcpLoggingServer.cs [hunk 5]
```diff
@@ -49,8 +52,14 @@ public TcpLoggingServer(IActorRef sinkCoordinator)
 
             Receive<Tcp.Received>(received =>
             {
-                var message = received.Data.ToString();
-                sinkCoordinator.Tell(message);
+                if (received.Data.Count >= BufferSize)
```
Comment (Arkatufus) [inline src/Akka.MultiNode.TestAdapter/TcpLoggingServer.cs:55]: This bug pertains to a lot of "unknown message" in our test. Although we don't have any limit on TCP message size, our buffer size is by default limited to 512 bytes, and since we pump messages as soon as we get them, if the string message is longer than 512 characters, the message will be chopped up. This happens a lot with FAIL-EXCEPTION messages since the stack trace can be quite big.

File: src/Akka.MultiNode.TestAdapter/Internal/Sinks/SinkCoordinator.cs (hunk 3 above)
Comment (Aaronontheweb) [reply src/Akka.MultiNode.TestAdapter/Internal/Sinks/SinkCoordinator.cs:203]: Yeah good idea to catch that then

File: src/Akka.MultiNode.TestAdapter/Internal/Sinks/FrameworkHandleMessageSinkActor.cs (hunk 1 above)
Comment (Aaronontheweb) [reply src/Akka.MultiNode.TestAdapter/Internal/Sinks/FrameworkHandleMessageSinkActor.cs:19]: Can you add an XML-DOC comment here to explain this?

File: src/Akka.MultiNode.TestAdapter/Internal/Sinks/MessageSink.cs [hunk 6]
```diff
@@ -112,15 +112,15 @@ public static MultiNodeTestRunnerMessageType DetermineMessageType(string message
             var matchRunnerLog = RunnerLogMessageRegex.Match(messageStr);
             if (matchRunnerLog.Success) return MultiNodeTestRunnerMessageType.RunnerLogMessage;
 
+            var matchFailureReason = NodeFailureReasonRegex.Match(messageStr);
```
Comment (Arkatufus) [inline src/Akka.MultiNode.TestAdapter/Internal/Sinks/MessageSink.cs:115]: Failure with exception need to be tested first, else the pass test will eat the exception messages because it contains the word "FAIL"

File: src/Akka.MultiNode.TestAdapter/TcpLoggingServer.cs (hunk 5 above)
Comment (Aaronontheweb) [reply src/Akka.MultiNode.TestAdapter/TcpLoggingServer.cs:55]: Can we increase the message size used by the MNTR in Akka.IO.Tcp?

**Review by Aaronontheweb — CHANGES_REQUESTED** [review]
Some small changes

**Comment by Aaronontheweb** [comment]
Looks good overall but left some remarks

**Comment by Arkatufus** [comment]
Increasing the buffer size would not actually fix the problem, because we'd never know how big the stack trace will be, a very deep stack trace with lots of inner exceptions

**Comment by Aaronontheweb** [comment]
@Arkatufus yeah but 512 is exceptionally tiny.

**Comment by Arkatufus** [comment]
I'll bump it up to 10 KB then? that should be a fairly safe number
